### ISSUE TITLE
Additions to documentation

### ISSUE THREAD

**Issue by raesche** [tangrams/PI-GPS#1]
Thanks for this great tutorial. I'm quiet a newby, so maybe my inputs may not be correct. 

I have followed the instructions step by step and I found two issues which seem to be wrong (at least not working in my Raspberry Pi setup).

**1. You suggest, that editing the config.yaml file for using local tiles should look like this:**
```
sources:
    osm:
        type: GeoJSONTiles
        url:  file:///home/pi/PI-GPS/build/bin/tiles/{z}-{x}-{y}.json
```

But I found that `type `should be left to MVT and the url file extension should be .mvt in order to work with the downloaded tiles (which are .mvt formatted)

So my changes in config.yaml look like this:
```
sources:
    osm:
        type: MVT
        url:  file:///home/pi/PI-GPS/build/bin/tiles/{z}-{x}-{y}.mvt
```

<br><br>

**2. Modifying config.yaml requires re-compilation**
It seems, that changes made do config.yaml are not taking effect until the following commands are issued:
```
cmake ..
make
```

I even use ```make -j 4``` to use all available cores (not sure if this is correct)

I think this should be mentioned in the tutorial since I don't find it obvious.

Thanks & best regards
Rashid
